// ------------------- Banner -------------------
export const BANNER_TEXT_ENGLISH = {
  title: "Systemic change starts with you",
  description:
    "Fund carbon removal, offsets, climate policy, and conservation–all in one subscription.",
  button_text: "Get started",
  description_text: "Join the 15,890 people who signed up this month!",
  avartar: ["avatar1.JPG"],
  name: [
    "Darren",
    "Dan",
    "PurchaserMark",
    "Tim",
    "Joe",
    "James",
    "Michael",
    "Corey",
    "Kaia",
    "Hanna",
  ],
  banner_footer: [
    " offset their carbon footprint! 2 hours ago",
    " offset their carbon footprint! 2 hours ago",
    " offset their carbon footprint! 2 hours ago",
    " offset their carbon footprint! 2 hours ago",
    " offset their carbon footprint! 3 hours ago",
    " offset their carbon footprint! 4 hours ago",
    " offset their carbon footprint! 3 hours ago",
    " offset their carbon footprint! 4 hours ago",
    " offset their carbon footprint! 4 hours ago",
    " offset their carbon footprint! 4 hours ago",
  ],
}

export const BANNER_TEXT_CHINESE = {
  title: "系统性变革从你我开始",
  description: "为碳减排、碳抵消、气候政策和保护生态做出贡献。",
  button_text: "开始",
  description_text: "这个月已有 15,890 人注册，加入我们！",
  avartar: ["avatar1.JPG"],
  name: [
    "Darren",
    "Dan",
    "PurchaserMark",
    "Tim",
    "Joe",
    "James",
    "Michael",
    "Corey",
    "Kaia",
    "Hanna",
  ],
  banner_footer: [
    " 抵消了他们的碳足迹！ 2 小时前",
    " 抵消了他们的碳足迹！ 2 小时前",
    " 抵消了他们的碳足迹！ 2 小时前",
    " 抵消了他们的碳足迹！ 2 小时前",
    " 抵消了他们的碳足迹！ 3 小时前",
    " 抵消了他们的碳足迹！ 4 小时前",
    " 抵消了他们的碳足迹！ 3 小时前",
    " 抵消了他们的碳足迹！ 4 小时前",
    " 抵消了他们的碳足迹！ 4 小时前",
    " 抵消了他们的碳足迹！ 4 小时前",
  ],
}

export const BANNER_IMAGE_URI = "irrawady.jfif"

// ------------------- Service -------------------

export const SERVICE_UTILS = {
  link: [
    "https://www.nytimes.com/2021/07/16/your-money/fight-climate-change.html",
    "https://www.wired.co.uk/article/net-zero-innovation-business",
    "https://www.forbes.com/sites/haleykim/2019/08/23/ycombinator-climate-change-wren-this-startup-will-offset-your-carbon-footprint/",
    "https://www.bloomberg.com/news/articles/2019-09-02/startups-sell-spotify-like-apps-to-offset-your-carbon-footprint",
  ],
  img: [
    "https://projectwren.imgix.net/wren-press-nyt.png?auto=format%2Ccompress&amp;q=35",
    "https://projectwren.imgix.net/wren-press-wired.png?auto=format%2Ccompress&q=35",
    "https://projectwren.imgix.net/wren-press-forbes-small.png?auto=format%2Ccompress&q=35",
    "https://projectwren.imgix.net/wren-press-bloomberg.png?auto=format%2Ccompress&q=35",
  ],
  text_english: [
    "Wren asks a series of questions to determine how much carbon you emit.",
    "Wren is making it easier for consumers to offset their carbon emissions.",
    "For less than $20 a month, Wren will offset your carbon footprint.",
    "Wren is one of a new breed of climate-centric startups for consumers.",
  ],
  text_chinese: [
    "Wren 提出了一系列方法来确定您的碳排放量。",
    "Wren 让您更容易抵消您的的碳排放量。",
    "每月只需不到 20 美元，Wren 就能抵消您的碳足迹。",
    "Wren 是面向用户的以保护气候为中心的初创公司之一。",
  ],
  max_width: ["200px", "135px", "90px", "150px"],
  delay: ["0s", "2s", "4s", "8s"],
  fade: ["fadeInOut-1", "fadeInOut-3", "fadeInOut-3", "fadeInOut-4"],
  index: [0, 1, 2, 3],
}

export const CLIMATE_ULTILS = {
  title: {
    chinese: ["Wren 承诺 ", "从你我开始", " 为保护气候做贡献"],
    english: ["Wren is your ", "all-in-one", " climate subscription."],
  },
  values: {
    numbers: ["$4.5M+", "700K+", "4.9★", "330K+"],
    description: {
      chinese: ["项目筹集资金", "贡献", "TrustPilot 评分", "二氧化碳抵消量"],
      english: [
        "Raised for projects",
        "Contributions",
        "TrustPilot score",
        "Tons of CO₂ offset",
      ],
    },
  },
}

export const STEP_UTILS = {
  videos: [
    "https://projectwren.imgix.net/how-it-works-calculator-fallback-img.jpg?auto=format%2Ccompress&q=35",
    "https://projectwren.imgix.net/how-it-works-calculator-fallback-img.jpg?auto=format%2Ccompress&q=35",
    "https://projectwren.imgix.net/how-it-works-project-updates-fallback-img.jpg?auto=format%2Ccompress&q=35",
  ],
  description: {
    number: ["1", "2", "3"],
    bracket: "bracket.svg",
    title: {
      english: [
        "Calculate your carbon footprint.",
        "Start a monthly subscription to fund climate solutions.",
        "See your impact grow every month.",
      ],
      chinese: [
        "计算您的碳足迹。",
        "开始每月订阅以资助气候解决方案。",
        "你的贡献每月都在增长。",
      ],
    },
    desc: {
      englsih: [
        "Use our intuitive calculator to find out how much CO₂ you emit.",
        "Maximise your impact by funding the climate solutions our planet needs.",
        "Receive updates that show how you’re making a positive impact on the climate.",
      ],
      chinese: [
        "使用我们的方法来计算您排放了多少二氧化碳。",
        "通过资助我们的气候解决方案来最大化您的贡献。",
        "实时了解您为气候变化做出的贡献。",
      ],
    },
    ref_text: {
      english: [
        "Data & research courtesy of:",
        "",
        "Member reviews on TrustPilot:",
      ],
      chinese: ["数据： ", "", "用户对 TrustPilot 的评价： "],
    },
    ref_img: [
      "https://projectwren.imgix.net/wren-data-and-research-partners.png?auto=format%2Ccompress&q=35&h=80",
      "",
      "https://projectwren.imgix.net/trustpilot-4-9.png?auto=format%2Ccompress&q=35",
    ],
  },
}

export const START_CLIMATE_UTILS = {
  title: {
    english: [
      "The climate crisis is a global problem.",
      "Be part of the solution.",
    ],
    chinese: ["气候危机是一个全球问题。", "让我们一起为防止气候危机做出贡献。"],
  },
  button: {
    english: "Get started",
    chinese: "开始",
  },
}

export const MEMBER_UTILS = {
  cssData: {
    left: [
      "5%",
      "15%",
      "25%",
      "35%",
      "45%",
      "55%",
      "65%",
      "75%",
      "85%",
      "95%",
      "10%",
      "28%",
      "38%",
      "48%",
      "58%",
      "68%",
      "78%",
      "88%",
      "5%",
      "20%",
    ],
    top: [
      "20%",
      "30%",
      "39%",
      "34%",
      "20%",
      "36%",
      "23%",
      "30%",
      "20%",
      "30%",
      "50%",
      "65%",
      "53%",
      "64%",
      "56%",
      "60%",
      "53%",
      "66%",
      "20%",
      "70%",
    ],
    img: [
      "https://projectwren.imgix.net/testimonials/cche.jpg?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/wren_profile.svg?auto=format%2Ccompress&q=35",
      "https://projectwren.imgix.net/investors/wren-paul-yacoubian.jpg?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/sally-profile.jpeg?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/celo.jpg?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/dyani.png?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/sarah.png?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/sarah.png?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/gustaf-profile.png?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/adrian.png?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/geoffrey.png?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/geoffrey.png?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/geoffrey.png?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/victor.png?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/ryan.jpg?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/delphine.jpg?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/lolitta.jpg?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/amelia.jpg?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/amelia.jpg?auto=format%2Ccompress&q=35&w=100",
      "https://projectwren.imgix.net/testimonials/amelia.jpg?auto=format%2Ccompress&q=35&w=100",
    ],
    width: [
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
    ],
    height: [
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
    ],
    radius: [
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
      "55px",
      "40px",
      "50px",
    ],
  },
  memberClick: {
    english: "Click on a face to read a review.",
    chinese: "单击头像阅读评论。",
  },
  memberData: {
    name: [
      "Armin Samii",
      "Korey Krauskopf",
      "Armin Samii",
      "Korey Krauskopf",
      "Armin Samii",
      "Korey Krauskopf",
      "Armin Samii",
      "Korey Krauskopf",
      "Armin Samii",
      "Korey Krauskopf",
      "Armin Samii",
      "Korey Krauskopf",
      "Armin Samii",
      "Korey Krauskopf",
      "Armin Samii",
      "Korey Krauskopf",
      "Armin Samii",
      "Korey Krauskopf",
      "Armin Samii",
      "Korey Krauskopf",
    ],
    username: [
      "@geoffreylitt",
      "@cche_n",
      "@geoffreylitt",
      "@cche_n",
      "@geoffreylitt",
      "@cche_n",
      "@geoffreylitt",
      "@cche_n",
      "@geoffreylitt",
      "@cche_n",
      "@geoffreylitt",
      "@cche_n",
      "@geoffreylitt",
      "@cche_n",
      "@geoffreylitt",
      "@cche_n",
      "@geoffreylitt",
      "@cche_n",
      "@geoffreylitt",
      "@cche_n",
    ],
    description: {
      english: [
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
        "Just signed up for @project_wren. Nice simple workflow: 1. calculate your carbon footprint 2. donate to specific, detailed, high-quality projects to offset your emissions (~$20/month)",
        "Wren is very open with both their intention, their processes and their execution. Very impressed with this service over the past year, will not only continue to be part of it but will increase my contribution.",
      ],
      chinese: [
        "刚刚注册@project_wren。简单高效的流程！：1。计算您的碳足迹2.",
        "Wren公开他们的目标和项目执行过程。过去一年的这个项目让我印象深刻，我会继续同Wren一起，为气候变化做出贡献。",
        "刚刚注册@project_wren。简单高效的流程！：1。计算您的碳足迹2.",
        "Wren公开他们的目标和项目执行过程。过去一年的这个项目让我印象深刻，我会继续同Wren一起，为气候变化做出贡献。",
        "刚刚注册@project_wren。简单高效的流程！：1。计算您的碳足迹2.",
        "Wren公开他们的目标和项目执行过程。过去一年的这个项目让我印象深刻，我会继续同Wren一起，为气候变化做出贡献。",
        "刚刚注册@project_wren。简单高效的流程！：1。计算您的碳足迹2.",
        "Wren公开他们的目标和项目执行过程。过去一年的这个项目让我印象深刻，我会继续同Wren一起，为气候变化做出贡献。",
        "刚刚注册@project_wren。简单高效的流程！：1。计算您的碳足迹2.",
        "Wren公开他们的目标和项目执行过程。过去一年的这个项目让我印象深刻，我会继续同Wren一起，为气候变化做出贡献。",
        "刚刚注册@project_wren。简单高效的流程！：1。计算您的碳足迹2.",
        "Wren公开他们的目标和项目执行过程。过去一年的这个项目让我印象深刻，我会继续同Wren一起，为气候变化做出贡献。",
        "刚刚注册@project_wren。简单高效的流程！：1。计算您的碳足迹2.",
        "Wren公开他们的目标和项目执行过程。过去一年的这个项目让我印象深刻，我会继续同Wren一起，为气候变化做出贡献。",
        "刚刚注册@project_wren。简单高效的流程！：1。计算您的碳足迹2.",
        "Wren公开他们的目标和项目执行过程。过去一年的这个项目让我印象深刻，我会继续同Wren一起，为气候变化做出贡献。",
        "刚刚注册@project_wren。简单高效的流程！：1。计算您的碳足迹2.",
        "Wren公开他们的目标和项目执行过程。过去一年的这个项目让我印象深刻，我会继续同Wren一起，为气候变化做出贡献。",
        "刚刚注册@project_wren。简单高效的流程！：1。计算您的碳足迹2.",
        "Wren公开他们的目标和项目执行过程。过去一年的这个项目让我印象深刻，我会继续同Wren一起，为气候变化做出贡献。",
      ],
    },
  },
}

export const GOAL_UTILS = {
  header_title: {
    chinese: ["我们的目标是针对气候危机", "采取简单有效的行动"],
    english: ["Our goal is to make climate action", "simple & effective"],
  },
}

export const WORK_UTILS = {
  img: [
    "https://projectwren.imgix.net/transparency-1.png?auto=format%2Ccompress&q=35",
    "https://projectwren.imgix.net/transparency-2.png?auto=format%2Ccompress&q=35",
    "https://projectwren.imgix.net/transparency-3.png?auto=format%2Ccompress&q=35",
  ],
  title: ["我们公开每一笔交易", "我们公开每一个项目", "我们公布每一张收据"],
  content: [
    "查看我们的进展。 每笔交易都有记录。",
    "在我们的回顾中了解我们的收入和资金流向。",
    "在我们的分类账上查看我们购买的每个碳信用额度。",
  ],
  link: ["/", "/", "/"],
  linkName: "查看",
}

export const FAQ_UTILS = {
  header_img:
    "	https://projectwren.imgix.net/circle-question-mark.png?auto=format%2Ccompress&q=35",
  title: "常见问题",
  quz: [
    "订阅后会发生什么？",
    "抵消我的碳足迹需要多少费用？",
    "为了防止气候危机，我还能做些什么？",
    "Wren的商业模式？",
  ],
  answers: [
    "作为订阅用户，您可以资助碳减排项目。 每个月，我们都会给您发送一封名为“您的贡献”的电子邮件，分享您资助的项目所取得的进展。 您可以访问我们的项目页面，了解有关我们项目的更多信息。",
    "抵消碳足迹的成本取决于您生活中产生的碳排放量，以及从大气中去除碳的成本。Wren 用户抵消其碳足迹的成本约为 23 美元。 许多人选择抵消一半或两倍的碳足迹。",
    "您应该做的第一件事是了解如何减少并抵消碳足迹。 您还可以邀请您身边的人一起为气候变化做出贡献。 大多数人没有意识到气候问题的紧迫性。 Extinction Rebellion 在他们的网站上有一些很棒的内容。最后，您可以积极参与政治活动。 地方政府正在为防止气候变化做出努力，因此您可以写信告诉他们您的建议。",
    "您订阅费用的 80% 会直接捐赠给气候项目，这些项目包括植树、保护雨林和从大气中吸取碳。 剩下的钱用于维持 Wren 的日常运营：支付薪水、寻找气候项目，以及支付营销费用以帮助尽可能多的人参与到气候变化的行动中。 我们的支付提供商 Stripe 会收取额外的手续费，以支付手续费，具体费用因支付方式而异。我们的费用意味着我们能够聘请世界上最优秀的人才，并和他们一起为气候变化做出贡献。 我们这一代最聪明的人正在优化谷歌和 Facebook 的广告。 只有付得起薪水，我们才能雇用这些人。",
  ],
}
